version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'monthly'
    ignore:
      # Ignores any major updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@types/eslint'
      commitlint:
        patterns:
          - '@commitlint/*'
      prettier:
        patterns:
          - 'prettier*'
      svgr:
        patterns:
          - '@svgr/*'
      figma-export:
        patterns:
          - '@figma-export/*'
      fs-extra:
        patterns:
          - 'fs-extra'
          - '@types/fs-extra'
      koobiq:
        patterns:
          - '@koobiq/*'
