version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'monthly'
    ignore:
      # Ignores any major updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      nx:
        patterns:
          - 'nx'
          - '@nx/*'
      angular:
        patterns:
          - '@angular/*'
          - '@angular-eslint/*'
          - 'ng-packagr'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - 'eslint-plugin-react*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'vite-*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - '@types/eslint'
      commitlint:
        patterns:
          - '@commitlint/*'
      prettier:
        patterns:
          - 'prettier*'
      svgr:
        patterns:
          - '@svgr/*'
      figma-export:
        patterns:
          - '@figma-export/*'
      koobiq:
        patterns:
          - '@koobiq/*'
