name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  general_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        uses: ./.github/workflows/actions/setup-yarn

      - name: Build packages
        run: yarn run build

      - name: Commitlint
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "${{ github.event.pull_request.title }}" | yarn commitlint

      - name: Linters
        run: |
          yarn run prettier
          yarn run eslint

      - name: Check Mapping
        run: yarn run check-mapping
