name: Publish

on:
  release:
    types:
      - created
  # Allows you to run this workflow manually
  workflow_dispatch:
    inputs:
      group:
        description: 'Release group to publish'
        required: true
        default: 'icons'
        type: choice
        options:
          - icons
          - visuals

permissions:
  contents: read
  packages: write
  # Needed for provenance data generation
  # https://nx.dev/recipes/nx-release/publish-in-ci-cd#npm-provenance
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'koobiq' }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Yarn
        uses: ./.github/workflows/actions/setup-yarn

      - name: Release Group
        id: group
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "name=${{ inputs.group }}" >> "$GITHUB_OUTPUT"
          elif echo "${{ github.event.release.tag_name }}" | grep -q "^@koobiq/visuals@"; then
            echo "name=visuals" >> "$GITHUB_OUTPUT"
          else
            echo "name=icons" >> "$GITHUB_OUTPUT"
          fi

      - run: yarn nx run-many -t build --projects=tag:$GROUP
        env:
          GROUP: ${{ steps.group.outputs.name }}

      - run: yarn nx release publish --group $GROUP --registry=$REGISTRY
        env:
          GROUP: ${{ steps.group.outputs.name }}
          REGISTRY: https://registry.npmjs.org/
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_KOOBIQ }}
          NPM_CONFIG_PROVENANCE: true

      - uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: ${{ secrets.MM_CHANNEL_NAME }}
          MATTERMOST_USERNAME: ${{ secrets.MM_BOT_NAME }}
          TEXT: ${{ github.event.release.body }}
